language: node_js
after_success: npm run report-coverage
deploy:
  provider: npm
  email: greenkeeper.keeper@gmail.com
  api_key:
    secure: HGMM3wehXosWL1YqqGmXQdYwdEYxwKLicacLQ+DdsSTRQpMa2ZAPElNxmFqUhtiXU9Fkrd+dkK0KQQolHMlAHHEMAxP80//SkHTMJaEQujEJGMGBpBsab4qXA6cbYSCnLMYrH6mAy4XINfzXwh0P1xTJiJT7leGJi2BATpLyrcYkO6ks7v5M9Tx+qGUH321KeeofUBdOP/0zDSdjWTdfSoc5esq9oTMedNJrqSJZP1vU5uSpx0qHYzfNWZ9kkrLRF9b5Bk3ocjWog5CxB06wF2qts62VcU3Vl+bzJ3UZLmyic07eCEFm39cdP1xntUSGxOjl6fXeVk0ARq1itchB/RiycaZzTA3I3VHT/FPEuwdeux/vrtG2IGnQYDjazXrZR3HrdR6v9lMnnp+rXKhRRKUO56Qwq//uR6UFNS+m9wpe3TvKHydYOcZ3rHMCuWMU4khBGF2/D5BhGtPbwvcSt7SCKZrI9Aytt1srjhc5+7+ZZAdUSk390VU7RLNFmyQItgcSICvAoepceFnrZpiJ7e9TXJEDL1bV6kXzzcunOl7pqSl4IoWP7hhFyKE5QohKPr1pLqZCsnq9b9fxPVLIcgyKMk38p7rj1BmnkeMHh3YA5Xlu7Z5Pw6cUGAFNfrNKWAcL+yN8bf5+38rHHIWieMvL8md6I/kApTT4V2erD9A=
  on:
    tags: true
    repo: greenkeeper-keeper/hapi-greenkeeper-keeper
