language: node_js
notifications:
  email: false
before_script:
- npm ls >/dev/null
- npm run greenkeeper:update-lockfile
after_script: npm run greenkeeper:upload-lockfile
after_success:
- npm run coverage:report
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: dxLhkkPS2+eViOAX5kryRW1zGuEYmq7i5qHwy2Bvnum3aXybCMVd6ke/EFLA2d2S5jUF/E21WLKwcdRJzAYDikdss+bhWbGO7E96CK6WWTypi7/rCn4yM5sYFViv2c75km0g3UJFRDK6xuap3ho9PC9P6sglHCEF8PeEBxcLI1xTs8iM9hHqmiHq7mBlX8H9mpsVf1rSsTOoDIa7V9K3lN6BsVnyv0ZHmfB/FTqeCl0nu7HCJDBu7PBX8LuyJ4e5T6lXGUKHwX/bpAb8dtoQNjYZgfrAiiI/8XVRWeT97Y8fMMZLm/+Uxd4bsBh5RsHjCEJFlRmkahrG+2r3VI1JoglUOB8eHUnWbweQF+EjI3n0utXWpfDBkNaodbO5k+9FhdGJGu3YgkmKRWXSYgpD63werEyj78TTVgR8WuuNBh2zQcxCQ4zHvbRDblce51KmT2nI06s+E6TQsXSO9CAOY21a2KPryMMtcVeMbtctb8HJ3vNWB8uGEWDTi60DjlCp/rzDQUnvV7RHI+1pnjGrit/PGvg/mmH537+TFyehibYuFpTpu1H4c4DwRWbxJBx2r4Fs5d31vHSv3/H63Ta07yJdqomHyPxi2eGwJFsqW1X9S7uDoJUGk9X+ox+cavtOMGzLJO4jlWQJumw5NMXOADlU9FAsUvZJoKZ0IjXB4xE=
