language: node_js
notifications:
  email: false
after_success:
- npm run coverage:report
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: V3VruISncX4C8btUot3VckSq1496EnBaieVw2xBBebeNLRvfV3e4Ukil6/42Zn6xI7wLIkaJy6ICn9OUgSCcyiJzCUfYU5RRWFR+ZXvWHuiw02sl8Y7wIy7E1wkTsHDSuI1Ys+BQkjPGVy3r/eDdbK8WcTP/ZxAM78Kv46tEPPZYSfyNJTmhySHJa7+djbGQGUYWvlklHS2YFc1v6bnLzg/+yZz99nfMndZv/nKD7za7c/G/w8cLmJ7i48fPIfaXXSj//R2zt2zkA73CeWDEUAR926T6dxnmJqrJBczekt0iNdwQ1QgdO3zscq1QvUXJ9u+GTM/FJhWfojjZAIlmKyWT4crF/6EjH104OlOSCzyxpqgvXonij6WyGhLTN8HKb1E0WM3erhfx51pY4xlIkCNgqM+DXFI+rh71hdWgLaeMteAC9WPtR2/UJE2g357M+lcvJi40Yvc6fLIlkReT0QrIs6tOWgEr9loh6TOv6RfDWzslbr7PXIuXD7Mum29a5oaltNUmfq/RFAN3BrSjzOkH1QSoaA5hU6+n380YljymzMkCzIzfm9LiLkXVuze4HMghAQmCzYqJzHp0n3t5eUFv7CAr8WYZ4esNeYf+XL9XdW9ITdJaRE7HOrCOAuUFCnZWtAVOx8OsnXzpYY/ub/lKUO1ZwtriunjG7fb/VB4=
  - secure: p56RyOVJE4gNPrU7LRU58wNeTjQipgcOWY4ktQxfedkQqnBJF+3hpqX8dCCo4LOUuc/K+N/eYDlznNYAh5jGHteCAfyFpQRqrdb2VG6Ffb/RMf1KmOdhBecMXvvqONQJM32GztYILDv0LlOJkwYf5QFxhpDZhLAN9NsYPu/61rwylDl+gadbl6tQnaJS0gBcF9+s4/gQnywdo0CAgitG7FK+dXOFVRnVX6dkJ4rrBEnKyNrbYIZCg3F/VcZjX9tHgASmo506IAqT7RxmevgrdK5FM/yzA3mMrBeXKtTLKR7kOmNTEuiNOaOTV+U8NdVx9+FDAWwvHsgPwkdU9vAuG8yuDmhjg2N1o7npGcfsylPQaiiZICpFzaP2bMvsIMeSJ+Zm0gFP5lbOFoc776SBur2jY8UB7oabYWC8h52AMsp7sC3rMtY4MN8QwSK+zt8mwqt3Bz99E17FE0bQa+ak3br2lHpkCzyX1OhFZ/1rh4VpnFV8HSxv5vXgK2+Fg8+aZ/KCq//cTsaaH545z2I0GvhlmPwj85AKvjHMqMxnYRvwBZqqwRT3YqyRqxx5d06uiG5pRlZKdhi9oIDqnHn65AR2wiLqz7gRzXXayV9uaSOh98mwgHalu4NK5ZClko4Q98mrYz6bZeQ/ep+3lz7SsnQhgvKL1DklJIbumsJLQXs=
