language: node_js
notifications:
  email: false
before_script: npm ls >/dev/null
after_success: npm run coverage:report
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
